"""The ingest Lambda, its Function URL, and the secret guarding it.

A Function URL rather than API Gateway: it costs nothing per request where an
HTTP API bills per million, and it's one less resource for a bot that handles a
few dozen requests a month.

The tradeoff is that a Function URL with auth type NONE is publicly reachable,
and a shared secret header is the only control. Mitigations, all of them load
bearing:

- The secret is generated by Secrets Manager, never checked into the repo.
- The handler compares it with ``hmac.compare_digest``.
- Reserved concurrency is capped, bounding what someone who finds the URL can
  spend on Bedrock before you notice.
- The handler rejects oversized bodies before doing any work.
- Bedrock and DynamoDB permissions are scoped to the one model and one table.
"""

from __future__ import annotations

import json

from aws_cdk import CfnOutput, Duration, RemovalPolicy, Stack
from aws_cdk import aws_dynamodb as dynamodb
from aws_cdk import aws_iam as iam
from aws_cdk import aws_lambda as lambda_
from aws_cdk import aws_logs as logs
from aws_cdk import aws_secretsmanager as secretsmanager
from constructs import Construct

from infra.config import DeployConfig

# Compiled bytecode from local test runs has no business in a deployment bundle.
ASSET_EXCLUDE = ["**/__pycache__", "**/*.pyc"]



class IngestApi(Construct):
    """Function URL + ingest Lambda + shared secret."""

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        table: dynamodb.ITable,
        config: DeployConfig,
        dry_run: bool,
    ) -> None:
        super().__init__(scope, construct_id)

        self.secret = secretsmanager.Secret(
            self,
            "SharedSecret",
            description=(
                "Shared secret the Apps Script watcher sends as the "
                "x-bill-bot-secret header. Copy it into Script Properties."
            ),
            generate_secret_string=secretsmanager.SecretStringGenerator(
                password_length=48,
                # Keep it header-safe: no quotes, spaces, or control characters.
                exclude_punctuation=True,
                exclude_characters=' "\'\\/@:;',
            ),
        )

        log_group = logs.LogGroup(
            self,
            "Logs",
            retention=logs.RetentionDays.ONE_MONTH,
            removal_policy=RemovalPolicy.DESTROY,
        )

        self.function = lambda_.Function(
            self,
            "Fn",
            runtime=lambda_.Runtime.PYTHON_3_12,
            handler="handler.handler",
            code=lambda_.Code.from_asset("lambdas/ingest", exclude=ASSET_EXCLUDE),
            # Bedrock on a long email is the slow part; well under the 30s an
            # Apps Script UrlFetchApp call will wait.
            timeout=Duration.seconds(60),
            memory_size=512,
            log_group=log_group,
            environment=runtime_environment(table, config, dry_run, self.secret),
        )

        # Bundle the shared modules alongside the handler.
        self.function.add_layers(shared_layer(self, table.stack))

        table.grant_read_write_data(self.function)
        self.secret.grant_read(self.function)
        grant_bedrock(self.function, config.bedrock_model_id, table.stack.region)

        self.url = self.function.add_function_url(
            auth_type=lambda_.FunctionUrlAuthType.NONE,
        )

        CfnOutput(
            self,
            "IngestUrl",
            value=self.url.url,
            description="Set as API_BASE_URL in Apps Script Script Properties",
        )
        CfnOutput(
            self,
            "SharedSecretArn",
            value=self.secret.secret_arn,
            description=(
                "Read the value with: aws secretsmanager get-secret-value "
                "--secret-id <arn> --query SecretString --output text"
            ),
        )


def runtime_environment(
    table: dynamodb.ITable,
    config: DeployConfig,
    dry_run: bool,
    secret: secretsmanager.ISecret,
) -> dict[str, str]:
    """Deploy-time constants the Lambdas read from the environment.

    Receivers and senders deliberately aren't here - they live in DynamoDB
    because they're the part you edit, and a table read keeps them consistent
    between the ingest and inbound handlers.
    """
    return {
        "TABLE_NAME": table.table_name,
        "BEDROCK_MODEL_ID": config.bedrock_model_id,
        "TIMEZONE": config.timezone,
        "DRY_RUN": "true" if dry_run else "false",
        "ON_LOW_CONFIDENCE": config.behavior.on_low_confidence,
        "NO_DUE_DATE_TEXT": config.behavior.no_due_date_text,
        "RECORD_TTL_DAYS": str(config.behavior.record_ttl_days),
        "VENMO_USERNAME": config.payee.venmo_username,
        "ZELLE_CONTACT": config.payee.zelle_contact or "",
        "PAYER_LABEL": config.payee.label,
        "PAYER_PHONE": config.payee.phone or "",
        "PAYER_SHARE": str(config.payee.share),
        "NOTIFY_ON_PAYMENT": "true" if config.payee.notify_on_payment else "false",
        "ORIGINATION_NUMBER_ID": config.messaging.origination_number_id,
        "SECRET_ARN": secret.secret_arn,
        "MESSAGES": json.dumps(
            {
                "bill": config.messages.bill,
                "paid_ack": config.messages.paid_ack,
                "status": config.messages.status,
                "reminder": config.messages.reminder,
                "payment_alert": config.messages.payment_alert,
                "venmo_note": config.messages.venmo_note,
            }
        ),
    }


def shared_layer(scope: Construct, stack: Stack) -> lambda_.ILayerVersion:
    """One layer holding lambdas/shared, reused by every function in the stack.

    The asset is ``lambdas/shared`` and the modules live in ``lambdas/shared/python``
    because that nesting is what makes a Python layer importable - layer content
    only reaches sys.path when it sits under ``python/``, arriving at
    ``/opt/python``. Flatten it and every import fails at runtime while tests
    still pass, since they read the files directly.

    Cached on the stack so multiple constructs asking for it get the same layer
    rather than uploading the same code twice.
    """
    cached = getattr(stack, "_bill_bot_shared_layer", None)
    if cached is not None:
        return cached

    layer = lambda_.LayerVersion(
        stack,
        "SharedLayer",
        code=lambda_.Code.from_asset(
            "lambdas/shared",
            exclude=ASSET_EXCLUDE,
        ),
        compatible_runtimes=[lambda_.Runtime.PYTHON_3_12],
        description="bill-bot shared modules (extract, shares, render, store)",
        removal_policy=RemovalPolicy.DESTROY,
    )
    stack._bill_bot_shared_layer = layer  # noqa: SLF001
    return layer


def grant_bedrock(fn: lambda_.Function, model_id: str, region: str) -> None:
    """Allow InvokeModel on exactly the configured model, nothing else.

    Cross-region inference profiles (the 'us.' prefix) route to several regions,
    so the profile and the underlying foundation models both need naming.
    """
    bare_model = model_id.split(".", 1)[1] if model_id.startswith("us.") else model_id
    fn.add_to_role_policy(
        iam.PolicyStatement(
            actions=["bedrock:InvokeModel"],
            resources=[
                f"arn:aws:bedrock:{region}:*:inference-profile/{model_id}",
                f"arn:aws:bedrock:*::foundation-model/{bare_model}",
            ],
        )
    )


def grant_sms_send_to_ingest(api: IngestApi, origination_number_id: str) -> None:
    """Let the ingest function send bill texts from the configured number.

    Imported lazily from the messaging construct to keep the grant logic in one
    place; skipped entirely when no number is configured, since dry-run never
    calls SendTextMessage.
    """
    from infra.constructs.messaging import grant_sms_send

    grant_sms_send(api.function, origination_number_id)
