// GENERATED by build/generate_senders_config.py from senders.config.json.
// Do not hand-edit - your changes will be overwritten. Add senders via
// `python setup/wizard.py --sender <address>` instead.

const SENDERS = [

];
